server:
  port: 8084
  servlet:
    context-path: /users
  error:
    include-message: always

management:
  health:
    livenessState.enabled: true
    readinessState.enabled: true
  endpoint.health.probes.enabled: true

spring:
  application:
    name: users-service
  datasource:
    password: password
    url: jdbc:postgresql://postgres:5432/user
    username: crbpavel
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      show-sql: true
  jackson:
    deserialization:
      FAIL_ON_IGNORED_PROPERTIES: false
    serialization:
      INDENT_OUTPUT: false
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_BIGDECIMAL_AS_PLAIN: true
  zipkin:
    base-url: http://zipkin:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka